title: 2023 EU Big Data hackathon
author: Eurostat
logo: EU.svg
copyright: "2023"
# execute:
#   execute_notebooks: force




  
  
repository:
  url: https://github.com/eurostat/eubd2023_docs  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

