title: 2023 EU Big Data hackathon
author: Eurostat
logo: EU.svg
copyright: "2023"
# execute:
#   execute_notebooks: force


repository:
  url: https://github.com/eurostat/eubd2023_docs  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  extra_footer : |
      <div>
      <a href="https://creativecommons.org/licenses/by/4.0/"><img src="https://licensebuttons.net/l/by/4.0/88x31.png"></a>
          All content on this site (unless otherwise specified) is licensed under the <a href="https://github.com/eurostat/eubd2023_docs/blob/main/LICENSE">CC BY 4.0 license</a>
      </div>

sphinx:
  config:
    html_show_copyright: false


